version: '3.2'

services:
  odopeyonexyz:
    image: johnyserpa/odopeyone
    build: .
    networks:
      - web
    volumes:
      - type: bind
        source: "./public_html"
        target: "/usr/local/apache2/htdocs/"

networks:
  web:
    external:
      name: web-server
